export const WEEKS_4_TO_6 = [
  {
    id: 4,
    title: "Şehirde Dolaşmak",
    subtitle: "Ulaşım, Yön Tarifi & Alışveriş",
    icon: "🚌",
    color: "#7B2D8B",
    vocabulary: [
      { gr: "Το λεωφορείο", pron: "To leoforío", tr: "Otobüs", category: "ulasim" },
      { gr: "Το μετρό", pron: "To metró", tr: "Metro", category: "ulasim" },
      { gr: "Το ταξί", pron: "To taksí", tr: "Taksi", category: "ulasim" },
      { gr: "Το πλοίο", pron: "To plío", tr: "Gemi / Feribot", category: "ulasim" },
      { gr: "Το εισιτήριο", pron: "To isitírio", tr: "Bilet", category: "ulasim" },
      { gr: "Η στάση", pron: "İ stási", tr: "Durak", category: "ulasim" },
      { gr: "Ευθεία", pron: "Efthía", tr: "Düz / İleri", category: "ulasim" },
      { gr: "Αριστερά", pron: "Aristerá", tr: "Sol", category: "ulasim" },
      { gr: "Δεξιά", pron: "Deksiá", tr: "Sağ", category: "ulasim" },
      { gr: "Κοντά", pron: "Kondá", tr: "Yakın", category: "ulasim" },
      { gr: "Μακριά", pron: "Makriá", tr: "Uzak", category: "ulasim" },
      { gr: "Το μαγαζί", pron: "To magazí", tr: "Dükkan", category: "alisveris" },
      { gr: "Η αγορά", pron: "İ agorá", tr: "Pazar / Çarşı", category: "alisveris" },
      { gr: "Ακριβό", pron: "Akrivó", tr: "Pahalı", category: "alisveris" },
      { gr: "Φτηνό", pron: "Ftinó", tr: "Ucuz", category: "alisveris" },
      { gr: "Πόσο κοστίζει;", pron: "Póso kostízi?", tr: "Ne kadar?", category: "alisveris" },
    ],
    dialogues: [
      {
        title: "Metro ile Akropolis'e Gitmek",
        setting: "Atina metrosunda bilet alıyorsunuz",
        lines: [
          { speaker: "Siz", gr: "Συγγνώμη, πώς πάω στην Ακρόπολη;", pron: "Signomi, pos pao stin Akropoli?", tr: "Affedersiniz, Akropolis'e nasıl giderim?" },
          { speaker: "Kişi", gr: "Πάρτε το μετρό, γραμμή δύο. Στάση «Ακρόπολη».", pron: "Parte to metro, grami dio. Stasi «Akropoli».", tr: "Metroyu alın, ikinci hat. «Akropolis» durağı." },
          { speaker: "Siz", gr: "Πού είναι ο σταθμός του μετρό;", pron: "Pu ine o stathmos tu metro?", tr: "Metro istasyonu nerede?" },
          { speaker: "Kişi", gr: "Ευθεία, μετά αριστερά. Πέντε λεπτά.", pron: "Efthia, meta aristera. Pende lepta.", tr: "Düz gidin, sonra sola. Beş dakika." },
          { speaker: "Siz", gr: "Πόσο κάνει το εισιτήριο;", pron: "Poso kani to isitírio?", tr: "Bilet ne kadar?" },
          { speaker: "Kişi", gr: "Ένα ευρώ και σαράντα.", pron: "Ena evro ke saranda.", tr: "Bir euro kırk sent." },
          { speaker: "Siz", gr: "Ευχαριστώ πολύ!", pron: "Efharisto poli!", tr: "Çok teşekkürler!" },
        ],
      },
      {
        title: "Hediyelik Eşya Alışverişi",
        setting: "Plaka'da bir hediyelik eşya dükkanında",
        lines: [
          { speaker: "Siz", gr: "Γεια σας! Πόσο κοστίζει αυτό;", pron: "Ya sas! Poso kostizi afto?", tr: "Merhaba! Bu ne kadar?" },
          { speaker: "Satıcı", gr: "Αυτό κοστίζει δεκαπέντε ευρώ.", pron: "Afto kostizi dekapende evro.", tr: "Bu on beş euro." },
          { speaker: "Siz", gr: "Είναι λίγο ακριβό. Κάνετε έκπτωση;", pron: "İne ligo akrivó. Kanete ekptosi?", tr: "Biraz pahalı. İndirim yapıyor musunuz?" },
          { speaker: "Satıcı", gr: "Αν πάρετε δύο, δέκα ευρώ το καθένα.", pron: "An parete dio, deka evro to kathena.", tr: "İki alırsanız, her biri on euro." },
          { speaker: "Siz", gr: "Εντάξει, θα πάρω δύο.", pron: "Endaksi, tha paro dio.", tr: "Tamam, iki alacağım." },
          { speaker: "Satıcı", gr: "Είκοσι ευρώ. Ευχαριστώ!", pron: "İkosi evro. Efharisto!", tr: "Yirmi euro. Teşekkürler!" },
        ],
      },
    ],
    reading: {
      title: "Μια μέρα στην Αθήνα",
      titleTr: "Atina'da Bir Gün",
      level: "A2",
      paragraphs: [
        { gr: "Σήμερα ξύπνησα νωρίς και πήρα το μετρό για την Ακρόπολη. Το εισιτήριο ήταν πολύ φτηνό, μόνο ένα ευρώ και σαράντα.", pron: "Simera ksipnisa noris ke pira to metro ya tin Akropoli. To isitírio itan poli ftinó, mono ena evro ke saranda.", tr: "Bugün erken kalktım ve Akropolis için metroyu aldım. Bilet çok ucuzdu, sadece bir euro kırk sent." },
        { gr: "Η Ακρόπολη ήταν εντυπωσιακή! Μετά, περπάτησα στην Πλάκα. Είδα πολλά μαγαζιά με αναμνηστικά. Αγόρασα ένα μικρό άγαλμα για δώρο.", pron: "İ Akropoli itan endiposiakí! Meta, perpatisa stin Plaka. İda pola magazia me anamnistiká. Agorasa ena mikro agalma ya doro.", tr: "Akropolis etkileyiciydi! Sonra Plaka'da yürüdüm. Hediyelik eşya satan birçok dükkan gördüm. Hediye olarak küçük bir heykel aldım." },
        { gr: "Το μεσημέρι, σταμάτησα σε μια ταβέρνα και έφαγα σουβλάκι. Ήταν πολύ νόστιμο και φτηνό. Μετά ήπια έναν ελληνικό καφέ.", pron: "To mesimeri, stamatisa se mia taverna ke efaga suvlaki. İtan poli nostimo ke ftinó. Meta ipia enan eliniko kafe.", tr: "Öğle vakti bir tavernada durdum ve souvlaki yedim. Çok lezzetli ve ucuzdu. Sonra bir Yunan kahvesi içtim." },
        { gr: "Το απόγευμα, πήγα στο Μοναστηράκι. Η αγορά εκεί είναι πολύ ενδιαφέρουσα. Υπάρχουν ρούχα, παπούτσια, βιβλία και πολλά άλλα. Λατρεύω την Αθήνα!", pron: "To apoyevma, piga sto Monastiraki. İ agora eki ine poli endiaferusa. İparhun ruha, paputsia, vivlia ke pola ala. Latrevo tin Athina!", tr: "Öğleden sonra Monastiraki'ye gittim. Oradaki çarşı çok ilginç. Kıyafetler, ayakkabılar, kitaplar ve daha birçok şey var. Atina'yı seviyorum!" },
        { gr: "Στο Μοναστηράκι συνάντησα μια Ελληνίδα που μιλούσε λίγο τουρκικά! Μου είπε ότι η γιαγιά της ήταν από την Κωνσταντινούπολη. Μιλήσαμε για τις δύο χώρες μας και γελάσαμε πολύ.", pron: "Sto Monastiraki sinandisa mia Elinida pu miluse ligo turkika! Mu ipe oti i yiayia tis itan apo tin Konstantinupoli. Milisame ya tis dio hores mas ke yelasame poli.", tr: "Monastiraki'de biraz Türkçe konuşan Yunanlı bir kadınla karşılaştım! Büyükannesinin İstanbul'dan olduğunu söyledi. İki ülkemiz hakkında konuştuk ve çok güldük." },
      ],
    },
    grammar: [
      "«Πώς πάω;» = Nasıl giderim? → Yol sormak için en kullanışlı kalıp.",
      "Yön tarifi: ευθεία (düz), αριστερά (sol), δεξιά (sağ), μετά (sonra).",
      "«Θα πάρω» = Alacağım → Alışverişte karar verdiğinizde kullanın.",
      "Geçmiş zaman: πήγα (gittim), είδα (gördüm), έφαγα (yedim), ήπια (içtim).",
    ],
  },
  {
    id: 5,
    title: "Günlük Hayat",
    subtitle: "Plaj, Hava Durumu, Saat & Acil Durumlar",
    icon: "🏖️",
    color: "#D4A017",
    vocabulary: [
      { gr: "Η παραλία", pron: "İ paralía", tr: "Plaj", category: "hava" },
      { gr: "Η θάλασσα", pron: "İ thálasa", tr: "Deniz", category: "hava" },
      { gr: "Ο ήλιος", pron: "O ílios", tr: "Güneş", category: "hava" },
      { gr: "Κάνει ζέστη", pron: "Káni zésti", tr: "Hava sıcak", category: "hava" },
      { gr: "Κάνει κρύο", pron: "Káni krío", tr: "Hava soğuk", category: "hava" },
      { gr: "Βρέχει", pron: "Vréhi", tr: "Yağmur yağıyor", category: "hava" },
      { gr: "Τι ώρα είναι;", pron: "Ti óra íne?", tr: "Saat kaç?", category: "temel" },
      { gr: "Σήμερα", pron: "Símera", tr: "Bugün", category: "temel" },
      { gr: "Αύριο", pron: "Ávrio", tr: "Yarın", category: "temel" },
      { gr: "Χθες", pron: "Hthés", tr: "Dün", category: "temel" },
      { gr: "Βοήθεια!", pron: "Voíthia!", tr: "Yardım!", category: "saglik" },
      { gr: "Γιατρός", pron: "Yatrós", tr: "Doktor", category: "saglik" },
      { gr: "Φαρμακείο", pron: "Farmakío", tr: "Eczane", category: "saglik" },
      { gr: "Αστυνομία", pron: "Astinomía", tr: "Polis", category: "saglik" },
      { gr: "Νοσοκομείο", pron: "Nosokomío", tr: "Hastane", category: "saglik" },
      { gr: "Δεν αισθάνομαι καλά", pron: "Den esthánome kalá", tr: "İyi hissetmiyorum", category: "saglik" },
    ],
    dialogues: [
      {
        title: "Plajda Bir Gün",
        setting: "Girit'te bir plajda şezlong kiralama",
        lines: [
          { speaker: "Siz", gr: "Γεια σας! Πόσο κοστίζει μία ξαπλώστρα;", pron: "Ya sas! Poso kostizi mia ksaplostra?", tr: "Merhaba! Bir şezlong ne kadar?" },
          { speaker: "Kişi", gr: "Δέκα ευρώ για δύο ξαπλώστρες και μία ομπρέλα.", pron: "Deka evro ya dio ksaplostres ke mia ombrela.", tr: "İki şezlong ve bir şemsiye on euro." },
          { speaker: "Siz", gr: "Τέλεια! Θα πάρω. Η θάλασσα είναι καθαρή;", pron: "Telia! Tha paro. İ thalasa ine kathari?", tr: "Mükemmel! Alacağım. Deniz temiz mi?" },
          { speaker: "Kişi", gr: "Πολύ καθαρή! Αλλά προσέξτε τον ήλιο, κάνει πολύ ζέστη.", pron: "Poli kathari! Ala prosekste ton ilio, kani poli zesti.", tr: "Çok temiz! Ama güneşe dikkat edin, çok sıcak." },
          { speaker: "Siz", gr: "Ναι, έχω αντηλιακό! Ευχαριστώ!", pron: "Ne, eho andiliako! Efharisto!", tr: "Evet, güneş kremim var! Teşekkürler!" },
        ],
      },
      {
        title: "Eczanede",
        setting: "Midin ağrıyor, eczaneye gidiyorsun",
        lines: [
          { speaker: "Siz", gr: "Γεια σας. Δεν αισθάνομαι καλά.", pron: "Ya sas. Den esthánome kala.", tr: "Merhaba. İyi hissetmiyorum." },
          { speaker: "Eczacı", gr: "Τι έχετε;", pron: "Ti ehete?", tr: "Neyiniz var?" },
          { speaker: "Siz", gr: "Πονάει το στομάχι μου.", pron: "Ponái to stomáhi mu.", tr: "Midem ağrıyor." },
          { speaker: "Eczacı", gr: "Φάγατε κάτι χθες;", pron: "Fagate kati hthes?", tr: "Dün bir şey yediniz mi?" },
          { speaker: "Siz", gr: "Ναι, έφαγα πολύ ψάρι στην ταβέρνα.", pron: "Ne, efaga poli psari stin taverna.", tr: "Evet, tavernada çok balık yedim." },
          { speaker: "Eczacı", gr: "Πάρτε αυτό, ένα χάπι πριν το φαγητό, τρεις μέρες.", pron: "Parte afto, ena hapi prin to fayito, tris meres.", tr: "Bunu alın, yemekten önce bir hap, üç gün." },
          { speaker: "Siz", gr: "Πόσο κάνει;", pron: "Poso kani?", tr: "Ne kadar?" },
          { speaker: "Eczacı", gr: "Πέντε ευρώ. Περαστικά!", pron: "Pende evro. Perastiká!", tr: "Beş euro. Geçmiş olsun!" },
          { speaker: "Siz", gr: "Ευχαριστώ πολύ!", pron: "Efharisto poli!", tr: "Çok teşekkürler!" },
        ],
      },
    ],
    reading: {
      title: "Καλοκαίρι στην Κρήτη",
      titleTr: "Girit'te Yaz",
      level: "A2-B1",
      paragraphs: [
        { gr: "Το καλοκαίρι στην Κρήτη είναι μαγικό. Ο ήλιος λάμπει κάθε μέρα και η θάλασσα είναι ζεστή και γαλάζια. Πολλοί τουρίστες έρχονται εδώ για τις παραλίες.", pron: "To kalokeri stin Kriti ine mayiko. O ilios lambi kathe mera ke i thalasa ine zesti ke galazia. Poli turistes erhonde edo ya tis paralies.", tr: "Girit'te yaz büyüleyici. Güneş her gün parlıyor ve deniz sıcak ve masmavi. Birçok turist plajlar için buraya geliyor." },
        { gr: "Χθες πήγα στην Ελαφονήσι. Είναι μία από τις πιο ωραίες παραλίες στον κόσμο. Η άμμος είναι ροζ και η θάλασσα τιρκουάζ. Κολύμπησα για ώρες!", pron: "Hthes piga stin Elafonisi. İne mia apo tis pio orees paralies ston kozmo. İ amos ine roz ke i thalasa tirkuaz. Kolimbisa ya ores!", tr: "Dün Elafonisi'ye gittim. Dünyanın en güzel plajlarından biri. Kum pembe ve deniz turkuaz. Saatlerce yüzdüm!" },
        { gr: "Δυστυχώς, σήμερα πονάει λίγο το κεφάλι μου — νομίζω ήπια πολύ κρασί χθες βράδυ! Πήγα στο φαρμακείο και πήρα ένα παυσίπονο.", pron: "Distihos, simera ponai ligo to kefali mu — nomizo ipia poli krasi hthes vradi! Piga sto farmakio ke pira ena pafsipono.", tr: "Maalesef bugün biraz başım ağrıyor — sanırım dün gece çok şarap içtim! Eczaneye gittim ve bir ağrı kesici aldım." },
        { gr: "Αύριο θα πάω στο Ηράκλειο για να δω το μουσείο. Θέλω να μάθω για τον πολιτισμό των Μινωιτών. Μετά, θα φάω κρητικό φαγητό — ντάκο, μεζέδες και ρακή!", pron: "Avrio tha pao sto İraklio ya na do to musio. Thelo na matho ya ton politizmo ton Minoiton. Meta, tha fao kritiko fayito — dako, mezedes ke raki!", tr: "Yarın müzeyi görmek için Heraklion'a gideceğim. Minos uygarlığını öğrenmek istiyorum. Sonra Girit yemeği yiyeceğim — dakos, meze ve rakı!" },
        { gr: "Η Κρήτη είναι ένα ξεχωριστό νησί. Εδώ νιώθεις την ιστορία παντού — στα αρχαία παλάτια, στα μικρά χωριά, ακόμα και στο φαγητό. Οι Κρητικοί είναι περήφανοι για τον τόπο τους και αυτό φαίνεται!", pron: "İ Kriti ine ena ksehoristo nisi. Edo niothis tin istoria pandu — sta arhea palatia, sta mikra horia, akoma ke sto fayito. İ Kritiki ine perifani ya ton topo tus ke afto fenete!", tr: "Girit benzersiz bir ada. Burada tarihi her yerde hissediyorsun — antik saraylarda, küçük köylerde, hatta yemekte bile. Giritliler memleketleriyle gurur duyuyor ve bu belli oluyor!" },
      ],
    },
    grammar: [
      "Hava durumu: «Κάνει ζέστη/κρύο» = Sıcak/soğuk. «Βρέχει» = Yağmur yağıyor.",
      "Ağrı ifadesi: «Πονάει + μου» → Πονάει το κεφάλι μου = Başım ağrıyor.",
      "Gelecek zaman: «Θα + fiil» → Θα πάω = Gideceğim, Θα φάω = Yiyeceğim.",
      "«Περαστικά!» = Geçmiş olsun! — Eczanede sıkça duyarsınız.",
    ],
  },
  {
    id: 6,
    title: "İleri Seviye Pratik",
    subtitle: "Sohbet, Feribot, Kültür & Genel Tekrar",
    icon: "🎓",
    color: "#2C3E50",
    vocabulary: [
      { gr: "Η Ελλάδα", pron: "İ Eláda", tr: "Yunanistan", category: "kultur" },
      { gr: "Η Τουρκία", pron: "İ Turkía", tr: "Türkiye", category: "kultur" },
      { gr: "Μου αρέσει", pron: "Mu arési", tr: "Hoşuma gidiyor", category: "kultur" },
      { gr: "Δεν μου αρέσει", pron: "Den mu arési", tr: "Hoşuma gitmiyor", category: "kultur" },
      { gr: "Νομίζω ότι...", pron: "Nomízo óti...", tr: "Düşünüyorum ki...", category: "kultur" },
      { gr: "Εντάξει", pron: "Endáksi", tr: "Tamam", category: "temel" },
      { gr: "Φυσικά", pron: "Fisiká", tr: "Tabii ki", category: "temel" },
      { gr: "Ίσως", pron: "Ísos", tr: "Belki", category: "temel" },
      { gr: "Λίγο", pron: "Lígo", tr: "Biraz", category: "temel" },
      { gr: "Πολύ", pron: "Polí", tr: "Çok", category: "temel" },
      { gr: "Πάντα", pron: "Pánda", tr: "Her zaman", category: "temel" },
      { gr: "Ποτέ", pron: "Poté", tr: "Asla", category: "temel" },
      { gr: "Η γνώμη μου", pron: "İ gnómi mu", tr: "Benim görüşüm", category: "kultur" },
      { gr: "Συμφωνώ", pron: "Simfonó", tr: "Katılıyorum", category: "kultur" },
      { gr: "Στην υγειά μας!", pron: "Stin iyá mas!", tr: "Sağlığımıza!", category: "kultur" },
      { gr: "Καλό ταξίδι!", pron: "Kaló taksídi!", tr: "İyi yolculuklar!", category: "kultur" },
    ],
    dialogues: [
      {
        title: "Yerel Biriyle Sohbet",
        setting: "Bir adada akşam yürüyüşünde bir Yunanlı ile sohbet",
        lines: [
          { speaker: "Yannis", gr: "Γεια σου! Είσαι τουρίστας;", pron: "Ya su! İse turístas?", tr: "Merhaba! Turist misin?" },
          { speaker: "Siz", gr: "Γεια σου! Ναι, είμαι από την Τουρκία.", pron: "Ya su! Ne, ime apo tin Turkia.", tr: "Merhaba! Evet, Türkiye'denim." },
          { speaker: "Yannis", gr: "Ωραία! Πώς σου φαίνεται η Ελλάδα;", pron: "Orea! Pos su fenete i Elada?", tr: "Güzel! Yunanistan sana nasıl geliyor?" },
          { speaker: "Siz", gr: "Μου αρέσει πολύ! Η θάλασσα, το φαγητό, οι άνθρωποι... Όλα είναι υπέροχα.", pron: "Mu aresi poli! İ thalasa, to fayito, i anthropi... Ola ine iperoha.", tr: "Çok hoşuma gidiyor! Deniz, yemek, insanlar... Her şey harika." },
          { speaker: "Yannis", gr: "Νομίζω ότι η Τουρκία και η Ελλάδα έχουν πολλά κοινά.", pron: "Nomizo oti i Turkia ke i Elada ehun pola kiná.", tr: "Türkiye ve Yunanistan'ın çok ortak noktası olduğunu düşünüyorum." },
          { speaker: "Siz", gr: "Συμφωνώ! Το φαγητό, η μουσική, η φιλοξενία... Είμαστε σαν αδέλφια!", pron: "Simfono! To fayito, i musiki, i filoksenia... İmaste san adelfia!", tr: "Katılıyorum! Yemek, müzik, misafirperverlik... Kardeş gibiyiz!" },
          { speaker: "Yannis", gr: "Ακριβώς! Θέλεις να πιούμε μαζί ένα ούζο;", pron: "Akrivós! Thelis na piume mazi ena uzo?", tr: "Aynen! Birlikte bir uzo içmek ister misin?" },
          { speaker: "Siz", gr: "Φυσικά! Στην υγειά μας!", pron: "Fisiká! Stin iyá mas!", tr: "Tabii ki! Sağlığımıza!" },
          { speaker: "Yannis", gr: "Στην υγειά μας!", pron: "Stin iyá mas!", tr: "Sağlığımıza!" },
        ],
      },
      {
        title: "Feribot Bileti Almak",
        setting: "Pire limanında ada feribotu için bilet alıyorsunuz",
        lines: [
          { speaker: "Siz", gr: "Γεια σας. Θέλω ένα εισιτήριο για τη Σαντορίνη.", pron: "Ya sas. Thelo ena isitírio ya ti Sandorini.", tr: "Merhaba. Santorini için bir bilet istiyorum." },
          { speaker: "Görevli", gr: "Για πότε;", pron: "Ya póte?", tr: "Ne zaman için?" },
          { speaker: "Siz", gr: "Για αύριο το πρωί.", pron: "Ya avrio to proi.", tr: "Yarın sabah için." },
          { speaker: "Görevli", gr: "Υπάρχει πλοίο στις εφτά και στις εννιά. Ποιο θέλετε;", pron: "İparhi plio stis efta ke stis enia. Pio thelete?", tr: "Yedide ve dokuzda gemi var. Hangisini istersiniz?" },
          { speaker: "Siz", gr: "Στις εννιά. Πόσο κοστίζει;", pron: "Stis enia. Poso kostizi?", tr: "Dokuzdaki. Ne kadar?" },
          { speaker: "Görevli", gr: "Σαράντα πέντε ευρώ. Κατάστρωμα ή κάμπινα;", pron: "Saranda pende evro. Katastroma i kabina?", tr: "Kırk beş euro. Güverte mi kabin mi?" },
          { speaker: "Siz", gr: "Κατάστρωμα. Πόση ώρα είναι το ταξίδι;", pron: "Katastroma. Posi ora ine to taksidi?", tr: "Güverte. Yolculuk kaç saat?" },
          { speaker: "Görevli", gr: "Περίπου πέντε ώρες. Ορίστε το εισιτήριό σας.", pron: "Perípu pende ores. Oriste to isitírio sas.", tr: "Yaklaşık beş saat. Biletiniz buyurun." },
          { speaker: "Siz", gr: "Ευχαριστώ! Από ποιο gate φεύγει;", pron: "Efharisto! Apo pio gate fevyi?", tr: "Teşekkürler! Hangi kapıdan kalkıyor?" },
          { speaker: "Görevli", gr: "Gate E7. Καλό ταξίδι!", pron: "Gate E7. Kaló taksídi!", tr: "E7 kapısı. İyi yolculuklar!" },
        ],
      },
    ],
    reading: {
      title: "Γείτονες και φίλοι",
      titleTr: "Komşular ve Dostlar",
      level: "B1",
      paragraphs: [
        { gr: "Η Ελλάδα και η Τουρκία είναι γείτονες. Μοιράζονται την ίδια θάλασσα, παρόμοιο φαγητό και πολλές κοινές λέξεις. Ο μπακάλης, ο μπαμπάς, το μπαλκόνι — αυτές οι λέξεις είναι ίδιες!", pron: "İ Elada ke i Turkia ine yitones. Mirazonde tin idia thalasa, paromio fayito ke poles kines leksis. O bakalis, o babas, to balkoni — aftes i leksis ine idies!", tr: "Yunanistan ve Türkiye komşudur. Aynı denizi, benzer yemekleri ve birçok ortak kelimeyi paylaşırlar. Bakkal, baba, balkon — bu kelimeler aynı!" },
        { gr: "Ο ελληνικός καφές μοιάζει πολύ με τον τούρκικο καφέ. Το γιαούρτι, οι μεζέδες, η ρακή — νομίζω ότι ένας Τούρκος αισθάνεται σαν στο σπίτι του στην Ελλάδα.", pron: "O elinikos kafes miazi poli me ton turkiko kafe. To yaúrti, i mezedes, i raki — nomizo oti enas Turkos esthánete san sto spiti tu stin Elada.", tr: "Yunan kahvesi Türk kahvesine çok benzer. Yoğurt, mezeler, rakı — bir Türk'ün Yunanistan'da kendini evinde gibi hissettiğini düşünüyorum." },
        { gr: "Πέρυσι ταξίδεψα στα ελληνικά νησιά για πρώτη φορά. Στη Ρόδο, ένας κύριος στην ταβέρνα μου είπε: «Καλώς ήρθες, φίλε! Εδώ είσαι σπίτι σου!» Αυτή η φιλοξενία μου θύμισε την Τουρκία.", pron: "Perisi taksidefsa sta elinika nisia ya proti fora. Sti Rodo, enas kirios stin taverna mu ipe: «Kalos irthes, file! Edo ise spiti su!» Afti i filoksenia mu thimise tin Turkia.", tr: "Geçen yıl ilk kez Yunan adalarına gittim. Rodos'ta tavernadaki bir bey bana dedi: «Hoş geldin dostum! Burası senin evin!» Bu misafirperverlik bana Türkiye'yi hatırlattı." },
        { gr: "Μαθαίνω ελληνικά εδώ και ένα μήνα. Δεν είναι πάντα εύκολο, αλλά κάθε μέρα μαθαίνω κάτι νέο. Το πιο σημαντικό; «Στην υγειά μας!» — γιατί η ζωή γιορτάζεται με παρέα, φαγητό και κρασί!", pron: "Matheno elinika edo ke ena mina. Den ine panda efkolo, ala kathe mera matheno kati neo. To pio simandiko? «Stin iyá mas!» — yati i zoi yortazete me parea, fayito ke krasi!", tr: "Bir aydır Yunanca öğreniyorum. Her zaman kolay değil, ama her gün yeni bir şey öğreniyorum. En önemli şey? «Sağlığımıza!» — çünkü hayat arkadaşlık, yemek ve şarapla kutlanır!" },
        { gr: "Όταν γυρίσω στην Τουρκία, θα πω σε όλους: «Πηγαίνετε στην Ελλάδα!» Θα τους δείξω τις φωτογραφίες μου και θα τους μιλήσω για τους φίλους που έκανα. Γιατί στο τέλος, δεν είμαστε απλά γείτονες — είμαστε φίλοι.", pron: "Otan yiriso stin Turkia, tha po se olus: «Piyenete stin Elada!» Tha tus dikso tis fotografies mu ke tha tus miliso ya tus filus pu ekana. Yati sto telos, den imaste apla yitones — imaste fili.", tr: "Türkiye'ye döndüğümde herkese diyeceğim: «Yunanistan'a gidin!» Onlara fotoğraflarımı göstereceğim ve edindiğim arkadaşlardan bahsedeceğim. Çünkü sonunda, biz sadece komşu değiliz — dostuz." },
      ],
    },
    grammar: [
      "«Μου αρέσει» = Hoşuma gidiyor → Türkçe'deki 'beğenmek'e yakın.",
      "«Νομίζω ότι...» = Düşünüyorum ki... → Fikir belirtmek için.",
      "«Στην υγειά μας!» = Sağlığımıza! → Kadeh kaldırırken mutlaka kullanın.",
      "Ortak kelimeler: μπακάλης=bakkal, μπαμπάς=baba, μπαλκόνι=balkon, γιαούρτι=yoğurt.",
    ],
  },
];
