export const WEEKS = [
  {
    id: 1,
    title: "Merhaba Yunanistan!",
    subtitle: "Alfabe, Selamlaşma & Temel İfadeler",
    icon: "🇬🇷",
    color: "#0D5EAF",
    vocabulary: [
      { gr: "Γεια σου", pron: "Ya su", tr: "Merhaba (tekil)", category: "selamlasma" },
      { gr: "Γεια σας", pron: "Ya sas", tr: "Merhaba (çoğul/resmi)", category: "selamlasma" },
      { gr: "Καλημέρα", pron: "Kalimera", tr: "Günaydın", category: "selamlasma" },
      { gr: "Καλησπέρα", pron: "Kalispera", tr: "İyi akşamlar", category: "selamlasma" },
      { gr: "Καληνύχτα", pron: "Kalinikta", tr: "İyi geceler", category: "selamlasma" },
      { gr: "Ευχαριστώ", pron: "Efharisto", tr: "Teşekkür ederim", category: "temel" },
      { gr: "Παρακαλώ", pron: "Parakalo", tr: "Rica ederim / Lütfen", category: "temel" },
      { gr: "Ναι", pron: "Ne", tr: "Evet", category: "temel" },
      { gr: "Όχι", pron: "Ohi", tr: "Hayır", category: "temel" },
      { gr: "Συγγνώμη", pron: "Signomi", tr: "Affedersiniz / Özür dilerim", category: "temel" },
      { gr: "Με λένε...", pron: "Me lene...", tr: "Benim adım...", category: "tanisma" },
      { gr: "Πώς σε λένε;", pron: "Pos se lene?", tr: "Adın ne?", category: "tanisma" },
      { gr: "Τι κάνεις;", pron: "Ti kanis?", tr: "Nasılsın?", category: "tanisma" },
      { gr: "Καλά, ευχαριστώ", pron: "Kala, efharisto", tr: "İyiyim, teşekkürler", category: "tanisma" },
      { gr: "Δεν καταλαβαίνω", pron: "Den katalaveno", tr: "Anlamıyorum", category: "temel" },
      { gr: "Μιλάτε τουρκικά;", pron: "Milate turkika?", tr: "Türkçe konuşuyor musunuz?", category: "temel" },
      { gr: "Μιλάω λίγο ελληνικά", pron: "Milao ligo elinika", tr: "Biraz Yunanca konuşuyorum", category: "temel" },
    ],
    numbers: [
      { gr: "ένα", pron: "ena", tr: "1" },
      { gr: "δύο", pron: "dio", tr: "2" },
      { gr: "τρία", pron: "tria", tr: "3" },
      { gr: "τέσσερα", pron: "tesera", tr: "4" },
      { gr: "πέντε", pron: "pende", tr: "5" },
      { gr: "έξι", pron: "eksi", tr: "6" },
      { gr: "εφτά", pron: "efta", tr: "7" },
      { gr: "οκτώ", pron: "okto", tr: "8" },
      { gr: "εννιά", pron: "enia", tr: "9" },
      { gr: "δέκα", pron: "deka", tr: "10" },
    ],
    dialogues: [
      {
        title: "Tanışma - İlk Karşılaşma",
        setting: "Atina'da bir kafede iki kişi tanışıyor",
        lines: [
          { speaker: "A", gr: "Γεια σου!", pron: "Ya su!", tr: "Merhaba!" },
          { speaker: "B", gr: "Γεια σου! Τι κάνεις;", pron: "Ya su! Ti kanis?", tr: "Merhaba! Nasılsın?" },
          { speaker: "A", gr: "Καλά, ευχαριστώ. Εσύ;", pron: "Kala, efharisto. Esi?", tr: "İyiyim, teşekkürler. Sen?" },
          { speaker: "B", gr: "Πολύ καλά! Πώς σε λένε;", pron: "Poli kala! Pos se lene?", tr: "Çok iyiyim! Adın ne?" },
          { speaker: "A", gr: "Με λένε Αλί. Εσένα;", pron: "Me lene Ali. Esena?", tr: "Benim adım Ali. Seninki?" },
          { speaker: "B", gr: "Με λένε Μαρία. Χαίρω πολύ!", pron: "Me lene Maria. Hero poli!", tr: "Benim adım Maria. Memnun oldum!" },
          { speaker: "A", gr: "Χαίρω πολύ! Μιλάω λίγο ελληνικά.", pron: "Hero poli! Milao ligo elinika.", tr: "Memnun oldum! Biraz Yunanca konuşuyorum." },
          { speaker: "B", gr: "Μπράβο! Πολύ ωραία!", pron: "Bravo! Poli orea!", tr: "Bravo! Çok güzel!" },
        ],
      },
      {
        title: "Yol Sorma - Basit",
        setting: "Sokakta bir yabancıya soru soruyorsunuz",
        lines: [
          { speaker: "A", gr: "Συγγνώμη!", pron: "Signomi!", tr: "Affedersiniz!" },
          { speaker: "B", gr: "Ναι; Παρακαλώ.", pron: "Ne? Parakalo.", tr: "Evet? Buyurun." },
          { speaker: "A", gr: "Μιλάτε τουρκικά;", pron: "Milate turkika?", tr: "Türkçe konuşuyor musunuz?" },
          { speaker: "B", gr: "Όχι, συγγνώμη. Μιλάω μόνο ελληνικά.", pron: "Ohi, signomi. Milao mono elinika.", tr: "Hayır, özür dilerim. Sadece Yunanca konuşuyorum." },
          { speaker: "A", gr: "Δεν πειράζει. Ευχαριστώ!", pron: "Den pirazi. Efharisto!", tr: "Sorun değil. Teşekkürler!" },
          { speaker: "B", gr: "Παρακαλώ! Γεια σου!", pron: "Parakalo! Ya su!", tr: "Rica ederim! Hoşça kal!" },
        ],
      },
    ],
    reading: {
      title: "Ο Αλί στην Αθήνα",
      titleTr: "Ali Atina'da",
      level: "A1 - Başlangıç",
      paragraphs: [
        { gr: "Γεια σας! Με λένε Αλί. Είμαι από την Τουρκία. Τώρα είμαι στην Αθήνα.", pron: "Ya sas! Me lene Ali. İme apo tin Turkia. Tora ime stin Athina.", tr: "Merhaba! Benim adım Ali. Türkiye'denim. Şimdi Atina'dayım." },
        { gr: "Η Αθήνα είναι πολύ ωραία. Μιλάω λίγο ελληνικά. Οι άνθρωποι είναι πολύ καλοί.", pron: "İ Athina ine poli orea. Milao ligo elinika. İ anthropi ine poli kali.", tr: "Atina çok güzel. Biraz Yunanca konuşuyorum. İnsanlar çok iyi." },
        { gr: "Καλημέρα! Καλησπέρα! Ευχαριστώ! Αυτά λέω κάθε μέρα.", pron: "Kalimera! Kalispera! Efharisto! Afta leo kathe mera.", tr: "Günaydın! İyi akşamlar! Teşekkürler! Bunları her gün söylüyorum." },
        { gr: "Σήμερα πήγα στο κέντρο της Αθήνας. Είδα την Ακρόπολη από μακριά. Ήταν πανέμορφη! Μετά περπάτησα στην Πλάκα και ήπια έναν καφέ.", pron: "Simera piga sto kentro tis Athinas. İda tin Akropoli apo makria. İtan panemorfi! Meta perpatisa stin Plaka ke ipia enan kafe.", tr: "Bugün Atina'nın merkezine gittim. Akropolis'i uzaktan gördüm. Muhteşemdi! Sonra Plaka'da yürüdüm ve bir kahve içtim." },
        { gr: "Οι Έλληνες είναι πολύ φιλικοί. Όταν ρώτησα για τον δρόμο, ένας κύριος με βοήθησε αμέσως. Μου είπε: «Ευθεία και μετά αριστερά!» Κατάλαβα!", pron: "İ Elines ine poli filiki. Otan rotisa ya ton dromo, enas kirios me voithise amesos. Mu ipe: «Efthia ke meta aristera!» Katalava!", tr: "Yunanlılar çok arkadaş canlısı. Yolu sorduğumda bir bey hemen bana yardım etti. Bana dedi: «Düz ve sonra sola!» Anladım!" },
      ],
    },
    grammar: [
      "Yunanca'da «Ναι» (Ne) = Evet, «Όχι» (Ohi) = Hayır. Türkçe'deki 'ne' ile karıştırmayın!",
      "«Γεια σου» tekil/samimi, «Γεια σας» çoğul/resmi kullanılır.",
      "«Είμαι» = (Ben) ...im/...yım → Είμαι από την Τουρκία = Türkiye'denim.",
      "Yunanca'da vurgu işareti (tonos) önemlidir: doğru heceye vurgu yapın.",
    ],
  },
  {
    id: 2,
    title: "Restoranda",
    subtitle: "Yemek Sipariş Etme & Hesap İsteme",
    icon: "🍽️",
    color: "#D4451A",
    vocabulary: [
      { gr: "Το εστιατόριο", pron: "To estiatório", tr: "Restoran", category: "yemek" },
      { gr: "Η ταβέρνα", pron: "İ taverna", tr: "Taverna", category: "yemek" },
      { gr: "Ο λογαριασμός", pron: "O logariasmos", tr: "Hesap", category: "yemek" },
      { gr: "Το μενού", pron: "To menú", tr: "Menü", category: "yemek" },
      { gr: "Το νερό", pron: "To neró", tr: "Su", category: "icecek" },
      { gr: "Το κρασί", pron: "To krasí", tr: "Şarap", category: "icecek" },
      { gr: "Η μπύρα", pron: "İ bíra", tr: "Bira", category: "icecek" },
      { gr: "Ο καφές", pron: "O kafés", tr: "Kahve", category: "icecek" },
      { gr: "Το ψωμί", pron: "To psomí", tr: "Ekmek", category: "yiyecek" },
      { gr: "Η σαλάτα", pron: "İ saláta", tr: "Salata", category: "yiyecek" },
      { gr: "Το ψάρι", pron: "To psári", tr: "Balık", category: "yiyecek" },
      { gr: "Το κρέας", pron: "To kréas", tr: "Et", category: "yiyecek" },
      { gr: "Θα ήθελα...", pron: "Tha íthela...", tr: "...istiyorum / ...isterim", category: "kalip" },
      { gr: "Τον λογαριασμό, παρακαλώ", pron: "Ton logariasmo, parakalo", tr: "Hesap, lütfen", category: "kalip" },
      { gr: "Είναι νόστιμο!", pron: "İne nóstimo!", tr: "Lezzetli!", category: "kalip" },
      { gr: "Ένα τραπέζι για δύο", pron: "Ena trapézi ya dío", tr: "İki kişilik bir masa", category: "kalip" },
      { gr: "Τι μου προτείνετε;", pron: "Ti mu protínete?", tr: "Ne önerirsiniz?", category: "kalip" },
    ],
    numbers: [
      { gr: "έντεκα", pron: "endeka", tr: "11" },
      { gr: "δώδεκα", pron: "dodeka", tr: "12" },
      { gr: "δεκαπέντε", pron: "dekapende", tr: "15" },
      { gr: "είκοσι", pron: "ikosi", tr: "20" },
      { gr: "τριάντα", pron: "trianda", tr: "30" },
      { gr: "σαράντα", pron: "saranda", tr: "40" },
      { gr: "πενήντα", pron: "peninda", tr: "50" },
      { gr: "εκατό", pron: "ekato", tr: "100" },
    ],
    dialogues: [
      {
        title: "Taverna'da Akşam Yemeği",
        setting: "Santorini'de deniz kenarında bir tavernada",
        lines: [
          { speaker: "Garson", gr: "Καλησπέρα! Πόσα άτομα;", pron: "Kalispera! Posa atoma?", tr: "İyi akşamlar! Kaç kişisiniz?" },
          { speaker: "Siz", gr: "Καλησπέρα! Δύο άτομα, παρακαλώ.", pron: "Kalispera! Dio atoma, parakalo.", tr: "İyi akşamlar! İki kişiyiz, lütfen." },
          { speaker: "Garson", gr: "Ορίστε, αυτό το τραπέζι. Ορίστε το μενού.", pron: "Oriste, afto to trapezi. Oriste to meniu.", tr: "Buyurun, bu masa. Menüyü alın." },
          { speaker: "Siz", gr: "Ευχαριστώ. Τι μου προτείνετε;", pron: "Efharisto. Ti mu protinete?", tr: "Teşekkürler. Ne önerirsiniz?" },
          { speaker: "Garson", gr: "Το ψάρι είναι πολύ φρέσκο σήμερα. Και η χωριάτικη σαλάτα.", pron: "To psari ine poli fresko simera. Ke i horiatiki salata.", tr: "Balık bugün çok taze. Ve köy salatası." },
          { speaker: "Siz", gr: "Θα ήθελα το ψάρι και μία σαλάτα, παρακαλώ.", pron: "Tha ithela to psari ke mia salata, parakalo.", tr: "Balık ve bir salata istiyorum, lütfen." },
          { speaker: "Garson", gr: "Τι θα πιείτε;", pron: "Ti tha piite?", tr: "Ne içersiniz?" },
          { speaker: "Siz", gr: "Ένα κρασί λευκό και ένα νερό.", pron: "Ena krasi lefko ke ena nero.", tr: "Bir beyaz şarap ve bir su." },
          { speaker: "Garson", gr: "Αμέσως!", pron: "Amesos!", tr: "Hemen!" },
          { speaker: "Siz", gr: "...Τον λογαριασμό, παρακαλώ.", pron: "...Ton logariasmo, parakalo.", tr: "...Hesap, lütfen." },
          { speaker: "Garson", gr: "Ορίστε. Είκοσι πέντε ευρώ.", pron: "Oriste. Ikosi pende evro.", tr: "Buyurun. Yirmi beş euro." },
          { speaker: "Siz", gr: "Ήταν πολύ νόστιμο! Ευχαριστώ πολύ!", pron: "İtan poli nostimo! Efharisto poli!", tr: "Çok lezzetliydi! Çok teşekkürler!" },
        ],
      },
      {
        title: "Kafede Sabah Kahvaltısı",
        setting: "Atina'da bir kafede sabah",
        lines: [
          { speaker: "Siz", gr: "Καλημέρα! Έναν καφέ, παρακαλώ.", pron: "Kalimera! Enan kafe, parakalo.", tr: "Günaydın! Bir kahve, lütfen." },
          { speaker: "Barista", gr: "Καλημέρα! Τι καφέ θέλετε; Ελληνικό ή φραπέ;", pron: "Kalimera! Ti kafe thelete? Eliniko i frape?", tr: "Günaydın! Ne kahve istersiniz? Yunan kahvesi mi frape mi?" },
          { speaker: "Siz", gr: "Έναν ελληνικό, μέτριο.", pron: "Enan eliniko, metrio.", tr: "Bir Yunan kahvesi, orta şekerli." },
          { speaker: "Barista", gr: "Θέλετε κάτι άλλο; Τυρόπιτα, μπουγάτσα;", pron: "Thelete kati alo? Tiropita, bugatsa?", tr: "Başka bir şey ister misiniz? Peynirli börek, bugatsa?" },
          { speaker: "Siz", gr: "Ναι, μία τυρόπιτα, παρακαλώ. Πόσο κάνει;", pron: "Ne, mia tiropita, parakalo. Poso kani?", tr: "Evet, bir peynirli börek, lütfen. Ne kadar?" },
          { speaker: "Barista", gr: "Τρία ευρώ και πενήντα.", pron: "Tria evro ke peninda.", tr: "Üç euro elli sent." },
          { speaker: "Siz", gr: "Ορίστε. Ευχαριστώ!", pron: "Oriste. Efharisto!", tr: "Buyurun. Teşekkürler!" },
        ],
      },
    ],
    reading: {
      title: "Φαγητό στην Ελλάδα",
      titleTr: "Yunanistan'da Yemek",
      level: "A1-A2",
      paragraphs: [
        { gr: "Το φαγητό στην Ελλάδα είναι πολύ νόστιμο. Οι Έλληνες τρώνε πολύ ψάρι, κρέας, σαλάτες και ψωμί.", pron: "To fayito stin Elada ine poli nostimo. İ Elines trone poli psari, kreas, salates ke psomi.", tr: "Yunanistan'da yemek çok lezzetli. Yunanlılar çok balık, et, salata ve ekmek yerler." },
        { gr: "Η χωριάτικη σαλάτα έχει ντομάτα, αγγούρι, ελιές, κρεμμύδι και φέτα. Είναι πολύ δημοφιλής.", pron: "İ horiatiki salata ehi domata, anguri, elies, kremidi ke feta. İne poli dimofilis.", tr: "Köy salatası domates, salatalık, zeytin, soğan ve beyaz peynir içerir. Çok popülerdir." },
        { gr: "Στην Ελλάδα πίνουμε πολύ καφέ. Ο ελληνικός καφές και ο φραπές είναι πολύ δημοφιλείς. Το καλοκαίρι, όλοι πίνουν φρέντο καπουτσίνο.", pron: "Stin Elada pinume poli kafe. O elinikos kafes ke o frapes ine poli dimofilís. To kalokeri, oli pinun fredo kaputsino.", tr: "Yunanistan'da çok kahve içeriz. Yunan kahvesi ve frape çok popülerdir. Yazın herkes soğuk cappuccino içer." },
        { gr: "Στις ταβέρνες, ο κόσμος τρώει αργά το βράδυ. Το δείπνο ξεκινάει στις εννιά ή στις δέκα. Οι Έλληνες αγαπούν το φαγητό και την παρέα!", pron: "Stis tavernes, o kozmos troi arga to vradi. To dipno ksekinai stis enia i stis deka. İ Elines agapun to fayito ke tin parea!", tr: "Tavernalarda insanlar akşam geç yer. Akşam yemeği dokuzda veya onda başlar. Yunanlılar yemeği ve arkadaş sohbetini severler!" },
        { gr: "Η μεσογειακή διατροφή είναι πολύ υγιεινή. Χρησιμοποιούμε πολύ ελαιόλαδο, λαχανικά, όσπρια και φρέσκα φρούτα. Ο γιαγιάς μου πάντα έλεγε: «Τρώγε σαν Έλληνας, ζήσε εκατό χρόνια!»", pron: "İ mesoyiaki diatrofi ine poli iyiini. Hrisimopioume poli eleolado, lahanika, ospria ke freska fruta. O yiayas mu panda elege: «Troge san Elinas, zise ekato hronia!»", tr: "Akdeniz diyeti çok sağlıklı. Bol zeytinyağı, sebze, baklagil ve taze meyve kullanırız. Büyükannem hep derdi: «Yunan gibi ye, yüz yıl yaşa!»" },
      ],
    },
    grammar: [
      "Yunanca'da artikeller: ο (erkek), η (dişi), το (nötr) — Türkçe'de karşılığı yoktur.",
      "«Θα ήθελα» (isterim) çok kibar bir sipariş kalıbıdır. Her yerde kullanın!",
      "«Πόσο κάνει;» = Ne kadar? → Fiyat sorarken kullanın.",
      "Kahve çeşitleri: μέτριο (orta şekerli), σκέτο (şekersiz), γλυκό (tatlı).",
    ],
  },
];

export const WEEKS_CONTINUED = [
  {
    id: 3,
    title: "Otelde",
    subtitle: "Rezervasyon, Check-in & İstekler",
    icon: "🏨",
    color: "#1A7A5C",
    vocabulary: [
      { gr: "Το ξενοδοχείο", pron: "To ksenodohío", tr: "Otel", category: "otel" },
      { gr: "Το δωμάτιο", pron: "To domátio", tr: "Oda", category: "otel" },
      { gr: "Η κράτηση", pron: "İ krátisi", tr: "Rezervasyon", category: "otel" },
      { gr: "Το κλειδί", pron: "To klidí", tr: "Anahtar", category: "otel" },
      { gr: "Η πισίνα", pron: "İ pisína", tr: "Havuz", category: "otel" },
      { gr: "Το πρωινό", pron: "To proinó", tr: "Kahvaltı", category: "otel" },
      { gr: "Μία νύχτα", pron: "Mía níhta", tr: "Bir gece", category: "otel" },
      { gr: "Μονόκλινο", pron: "Monóklino", tr: "Tek kişilik oda", category: "otel" },
      { gr: "Δίκλινο", pron: "Díklino", tr: "İki kişilik oda", category: "otel" },
      { gr: "Με θέα θάλασσα", pron: "Me théa thálasa", tr: "Deniz manzaralı", category: "otel" },
      { gr: "Το κλιματιστικό", pron: "To klimatistikó", tr: "Klima", category: "otel" },
      { gr: "Η πετσέτα", pron: "İ petséta", tr: "Havlu", category: "otel" },
      { gr: "Έχετε...;", pron: "Éhete...?", tr: "...var mı?", category: "kalip" },
      { gr: "Πού είναι...;", pron: "Pu íne...?", tr: "...nerede?", category: "kalip" },
      { gr: "Χρειάζομαι...", pron: "Hriázome...", tr: "...ihtiyacım var", category: "kalip" },
      { gr: "Δεν δουλεύει", pron: "Den dulevi", tr: "Çalışmıyor", category: "kalip" },
    ],
    dialogues: [
      {
        title: "Otel Check-in",
        setting: "Mikonos'ta bir otelin resepsiyonunda",
        lines: [
          { speaker: "Siz", gr: "Καλησπέρα! Έχω κράτηση.", pron: "Kalispera! Eho kratisi.", tr: "İyi akşamlar! Rezervasyonum var." },
          { speaker: "Resepsiyon", gr: "Καλησπέρα! Σε ποιο όνομα;", pron: "Kalispera! Se pio onoma?", tr: "İyi akşamlar! Hangi isim üzerine?" },
          { speaker: "Siz", gr: "Στο όνομα Γιλμάζ. Για τρεις νύχτες.", pron: "Sto onoma Yilmaz. Ya tris nihtes.", tr: "Yılmaz adına. Üç gece için." },
          { speaker: "Resepsiyon", gr: "Ναι, σας βρήκα. Δίκλινο με θέα θάλασσα. Σωστά;", pron: "Ne, sas vrika. Diklino me thea thalasa. Sosta?", tr: "Evet, buldum. Deniz manzaralı iki kişilik oda. Doğru mu?" },
          { speaker: "Siz", gr: "Ναι, σωστά! Το πρωινό περιλαμβάνεται;", pron: "Ne, sosta! To proino perilamvanete?", tr: "Evet, doğru! Kahvaltı dahil mi?" },
          { speaker: "Resepsiyon", gr: "Ναι, από τις εφτά μέχρι τις δέκα. Ορίστε το κλειδί σας. Δωμάτιο 205.", pron: "Ne, apo tis efta mehri tis deka. Oriste to klidi sas. Domatio diakosia pende.", tr: "Evet, yediden ona kadar. Anahtarınız buyurun. Oda 205." },
          { speaker: "Siz", gr: "Υπάρχει πισίνα;", pron: "İparhi pisina?", tr: "Havuz var mı?" },
          { speaker: "Resepsiyon", gr: "Ναι, στον τρίτο όροφο.", pron: "Ne, ston trito orofo.", tr: "Evet, üçüncü katta." },
          { speaker: "Siz", gr: "Τέλεια! Ευχαριστώ πολύ!", pron: "Telia! Efharisto poli!", tr: "Mükemmel! Çok teşekkürler!" },
        ],
      },
      {
        title: "Odada Sorun Var!",
        setting: "Otel odasında sorun bildirme",
        lines: [
          { speaker: "Siz", gr: "Συγγνώμη, έχω ένα πρόβλημα.", pron: "Signomi, eho ena provlima.", tr: "Özür dilerim, bir sorunum var." },
          { speaker: "Resepsiyon", gr: "Τι πρόβλημα έχετε;", pron: "Ti provlima ehete?", tr: "Ne sorununuz var?" },
          { speaker: "Siz", gr: "Το κλιματιστικό δεν δουλεύει.", pron: "To klimatistiko den dulevi.", tr: "Klima çalışmıyor." },
          { speaker: "Resepsiyon", gr: "Ω, συγγνώμη! Θα στείλω κάποιον αμέσως.", pron: "O, signomi! Tha stilo kapion amesos.", tr: "Ah, özür dilerim! Hemen birini göndereceğim." },
          { speaker: "Siz", gr: "Επίσης, χρειάζομαι πετσέτες.", pron: "Episis, hriazome petsetes.", tr: "Ayrıca havlulara ihtiyacım var." },
          { speaker: "Resepsiyon", gr: "Βεβαίως! Κάτι άλλο;", pron: "Veveos! Kati alo?", tr: "Tabii ki! Başka bir şey?" },
          { speaker: "Siz", gr: "Όχι, ευχαριστώ. Αυτά.", pron: "Ohi, efharisto. Afta.", tr: "Hayır, teşekkürler. Bu kadar." },
        ],
      },
    ],
    reading: {
      title: "Το ξενοδοχείο μου στη Σαντορίνη",
      titleTr: "Santorini'deki Otelim",
      level: "A2",
      paragraphs: [
        { gr: "Μένω σε ένα μικρό ξενοδοχείο στη Σαντορίνη. Το δωμάτιό μου είναι μικρό αλλά πολύ όμορφο. Έχει θέα στη θάλασσα και ένα μικρό μπαλκόνι.", pron: "Meno se ena mikro ksenodohio sti Sandorini. To domatio mu ine mikro ala poli omorfo. Ehi thea sti thalasa ke ena mikro balkoni.", tr: "Santorini'de küçük bir otelde kalıyorum. Odam küçük ama çok güzel. Deniz manzarası ve küçük bir balkonu var." },
        { gr: "Κάθε πρωί τρώω πρωινό στην αυλή. Υπάρχει γιαούρτι με μέλι, φρούτα, τυρόπιτα και καφές. Το πρωινό είναι πολύ νόστιμο.", pron: "Kathe proi troo proino stin avli. İparhi yaúrti me meli, fruta, tiropita ke kafes. To proino ine poli nostimo.", tr: "Her sabah avluda kahvaltı yapıyorum. Ballı yoğurt, meyve, peynirli börek ve kahve var. Kahvaltı çok lezzetli." },
        { gr: "Οι υπάλληλοι του ξενοδοχείου είναι πολύ ευγενικοί. Μιλάνε αργά και με βοηθάνε. Χθες ρώτησα πού είναι η παραλία και μου εξήγησαν πολύ καλά.", pron: "İ ipalili tu ksenodohiu ine poli evyenikí. Milane arga ke me voithane. Hthes rotisa pu ine i paralia ke mu eksiyisan poli kala.", tr: "Otel çalışanları çok kibar. Yavaş konuşuyorlar ve bana yardım ediyorlar. Dün plajın nerede olduğunu sordum ve çok iyi açıkladılar." },
        { gr: "Το ξενοδοχείο έχει μία μικρή πισίνα στην ταράτσα. Από εκεί βλέπεις όλη τη θάλασσα και το ηλιοβασίλεμα. Είναι μαγικό! Κάθε βράδυ κάθομαι εκεί και πίνω ένα ποτήρι κρασί.", pron: "To ksenodohio ehi mia mikri pisina stin taratsa. Apo eki vlepis oli ti thalasa ke to iliovasilema. İne mayiko! Kathe vradi kathome eki ke pino ena potiri krasi.", tr: "Otelin çatı katında küçük bir havuzu var. Oradan tüm denizi ve gün batımını görüyorsun. Büyüleyici! Her akşam orada oturup bir kadeh şarap içiyorum." },
        { gr: "Αύριο θα ρωτήσω στη ρεσεψιόν αν μπορούν να κλείσουν ένα εστιατόριο για μένα. Θέλω να δοκιμάσω το τοπικό κρασί και τα τοπικά φαγητά της Σαντορίνης.", pron: "Avrio tha rotiso sti resepsion an borun na klisun ena estiatorio ya mena. Thelo na dokimaso to topiko krasi ke ta topika fayita tis Sandorinis.", tr: "Yarın resepsiyona bir restoran rezervasyonu yapıp yapamayacaklarını soracağım. Santorini'nin yerel şarabını ve yerel yemeklerini denemek istiyorum." },
      ],
    },
    grammar: [
      "«Έχω» = ...var (bende) / «Έχετε» = ...var mı (sizde) → Έχετε δωμάτιο; = Odanız var mı?",
      "«Υπάρχει» = Var (genel) → Υπάρχει πισίνα; = Havuz var mı?",
      "«Δεν» = olumsuzluk eki → Δεν δουλεύει = Çalışmıyor",
      "Sayılarda: 200=διακόσια, 205=διακόσια πέντε.",
    ],
  },
];

export const SCHEDULE = [
  { week: "1. Hafta", days: "1-7. gün", focus: "Alfabe, selamlaşma, sayılar (1-10), temel kalıplar", daily: "Kelime çalışması (20dk) → Diyalog okuma (20dk) → Okuma parçası (20dk)" },
  { week: "2. Hafta", days: "8-14. gün", focus: "Restoran, sipariş verme, hesap isteme, sayılar (11-100)", daily: "Kelime tekrarı + yeni (20dk) → Diyalog pratiği (25dk) → Okuma + gramer (15dk)" },
  { week: "3. Hafta", days: "15-21. gün", focus: "Otel check-in, sorun bildirme, isteklerde bulunma", daily: "Genel tekrar 1-2 hafta (15dk) → Yeni diyaloglar (25dk) → Okuma parçası (20dk)" },
  { week: "4. Hafta", days: "22-28. gün", focus: "Ulaşım, yön tarifi, alışveriş, pazarlık", daily: "Kelime çalışması (20dk) → Diyalog pratiği (25dk) → Okuma + gramer (15dk)" },
  { week: "5. Hafta", days: "29-35. gün", focus: "Plaj, hava durumu, sağlık, acil durumlar", daily: "Genel tekrar 3-4 hafta (15dk) → Yeni diyaloglar (25dk) → Okuma parçası (20dk)" },
  { week: "6. Hafta", days: "36-45. gün", focus: "Sohbet, feribot, kültür, genel tekrar", daily: "Toplam tekrar (20dk) → İleri diyaloglar (20dk) → Uzun okuma parçası (20dk)" },
];

export const CATEGORIES = {
  selamlasma: "Selamlaşma",
  temel: "Temel İfadeler",
  tanisma: "Tanışma",
  yemek: "Yemek & Restoran",
  icecek: "İçecekler",
  yiyecek: "Yiyecekler",
  kalip: "Kalıp İfadeler",
  otel: "Otel",
  ulasim: "Ulaşım",
  alisveris: "Alışveriş",
  saglik: "Sağlık",
  hava: "Hava Durumu",
  kultur: "Kültür"
};
